# Generated by Django 6.0.2 on 2026-02-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
        ('tender_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=80)),
                ('date_signature', models.DateTimeField()),
                ('statut', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_contractant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.servicecontractant')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(max_length=30)),
                ('date_depot', models.DateTimeField()),
                ('decision', models.TextField()),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('operateur_economique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.operateureconomique')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_service.utilisateur')),
                ('validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.validation')),
            ],
        ),
    ]
