# Generated by Django 6.0.2 on 2026-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('related_type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('type_document', models.CharField(max_length=50)),
                ('storage_url', models.CharField(max_length=500, unique=True)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('ia_verif_statut', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('ANOMALY', 'Anomaly')], default='PENDING', max_length=30)),
                ('ia_verif_details', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
