# Generated by Django 6.0.2 on 2026-02-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='taille_fichier',
            field=models.BigIntegerField(default=0),
        ),
    ]
