# Generated by Django 6.0.2 on 2026-02-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_service', '0002_document_taille_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visible_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
