# Generated by Django 5.1.6 on 2026-05-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs_service', '0002_demandeoperateur_motif_rejet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembresTutelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membre', models.UUIDField(db_index=True)),
                ('tutelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membre_links', to='acteurs_service.tutelle')),
            ],
            options={
                'db_table': 'Membres_Tutelle',
                'constraints': [models.UniqueConstraint(fields=('id_membre', 'tutelle'), name='unique_membre_tutelle')],
            },
        ),
    ]
