# Generated by Django 5.1.6 on 2026-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acteurs_service', '0003_membrestutelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutelle',
            name='organisation',
        ),
        migrations.AddField(
            model_name='commissionexterne',
            name='niveau_competence',
            field=models.CharField(choices=[('WILAYA', 'Wilaya'), ('SECTORIELLE', 'Sectorielle'), ('NATIONAL', 'National')], default='WILAYA', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionexterne',
            name='seuil',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type_entite',
            field=models.CharField(choices=[('OPERATEUR_ECONOMIQUE', 'Opérateur Économique'), ('SERVICE_CONTRACTANT', 'Service Contractant'), ('COMMISSION_EXTERNE', 'Commission Externe')], default='OPERATEUR_ECONOMIQUE', max_length=30),
        ),
        migrations.DeleteModel(
            name='MembresTutelle',
        ),
        migrations.DeleteModel(
            name='Tutelle',
        ),
    ]
