# Generated by Django 6.0.2 on 2026-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('entite_type', models.CharField(max_length=50)),
                ('entite_id', models.BigIntegerField()),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('details_action', models.JSONField()),
                ('hash_precedent', models.BinaryField()),
                ('hash_actuel', models.BinaryField()),
                ('signature', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journaux_audit',
                'indexes': [models.Index(fields=['utilisateur_id'], name='journaux_au_utilisa_797c72_idx'), models.Index(fields=['entite_type', 'entite_id'], name='journaux_au_entite__eb0ee4_idx'), models.Index(fields=['horodatage'], name='journaux_au_horodat_8bb8bf_idx')],
            },
        ),
    ]
