# Generated by Django 6.0.2 on 2026-02-28 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=150)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], db_index=True, default='PENDING', max_length=20)),
                ('trace_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'journaux_outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='journaux_ou_aggrega_5a8570_idx'), models.Index(fields=['event_type', 'status'], name='journaux_ou_event_t_f119fe_idx')],
            },
        ),
    ]
