# Generated by Django 6.0.3 on 2026-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoursModel',
            fields=[
                ('id_recours', models.AutoField(primary_key=True, serialize=False)),
                ('id_operateur_economique', models.IntegerField()),
                ('id_validation', models.IntegerField()),
                ('id_soumission', models.IntegerField(unique=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('DEPOSE', 'DEPOSE'), ('EN_INSTRUCTION', 'EN_INSTRUCTION'), ('DECISION_PRISE', 'DECISION_PRISE'), ('ACCEPTE', 'ACCEPTE'), ('REJETE', 'REJETE'), ('CLOTURE', 'CLOTURE')], max_length=50)),
                ('date_depot', models.DateTimeField()),
                ('date_limite', models.DateTimeField()),
                ('decision', models.TextField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recours',
            },
        ),
        migrations.CreateModel(
            name='DocumentRecoursModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_recours', models.IntegerField()),
                ('id_document', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents_recours',
                'unique_together': {('id_recours', 'id_document')},
            },
        ),
    ]
