from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recours", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS recours (
                id_recours integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_operateur_economique integer NOT NULL,
                id_validation integer NOT NULL,
                id_soumission integer NOT NULL UNIQUE,
                motif text NOT NULL,
                statut varchar(50) NOT NULL,
                date_depot timestamptz NOT NULL,
                date_limite timestamptz NOT NULL,
                decision text NULL,
                date_decision timestamptz NULL,
                traite_par integer NULL,
                version integer NOT NULL DEFAULT 0,
                created_at timestamptz NOT NULL DEFAULT NOW(),
                updated_at timestamptz NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS documents_recours (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_recours integer NOT NULL,
                id_document integer NOT NULL,
                created_at timestamptz NOT NULL DEFAULT NOW(),
                CONSTRAINT documents_recours_unique_recours_document
                    UNIQUE (id_recours, id_document)
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS documents_recours;
            DROP TABLE IF EXISTS recours;
            """,
        ),
    ]
