# Generated by Django 5.1.6 on 2026-05-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recours', '0003_mobile_form_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentrecoursmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recoursmodel',
            name='date_fin_instruction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentrecoursmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentrecoursmodel',
            name='id_recours',
            field=models.ForeignKey(db_column='id_recours', on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='recours.recoursmodel'),
        ),
        migrations.AddConstraint(
            model_name='documentrecoursmodel',
            constraint=models.UniqueConstraint(fields=('id_recours', 'id_document'), name='documents_recours_unique_recours_document'),
        ),
    ]
