# Generated by Django 5.1.6 on 2026-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recours', '0004_alter_documentrecoursmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoursmodel',
            name='date_fin_instruction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
