class DjangoRecoursRepository:

    def save(self, recours): ...
    def get_by_id(self, recours_id: int): ...
    def get_by_soumission(self, soumission_id: int): ...
    def list(self, filters: dict): ...
    def delete(self, recours_id: int): ...