# Generated by Django 5.2.11 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogRead',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('utilisateur_id', models.BigIntegerField(db_index=True)),
                ('action', models.CharField(max_length=100)),
                ('entite_type', models.CharField(db_index=True, max_length=50)),
                ('entite_id', models.BigIntegerField(db_index=True)),
                ('horodatage', models.DateTimeField(db_index=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('details_action', models.JSONField()),
            ],
            options={
                'db_table': 'audit_read_projection',
                'managed': True,
                'indexes': [models.Index(fields=['entite_type', 'entite_id'], name='audit_read__entite__362e78_idx'), models.Index(fields=['utilisateur_id', 'horodatage'], name='audit_read__utilisa_9f84da_idx')],
            },
        ),
    ]
