# Generated by Django 5.1.6 on 2026-03-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionEvaluation',
            fields=[
                ('id_comission', models.AutoField(primary_key=True, serialize=False)),
                ('id_service', models.IntegerField()),
                ('nom_comission', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comission_evaluation',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evalution', models.AutoField(primary_key=True, serialize=False)),
                ('id_soumission', models.IntegerField()),
                ('id_utilisateur', models.IntegerField()),
                ('type', models.CharField(choices=[('administrative', 'Administrative'), ('technique', 'Technique'), ('financière', 'Financière')], max_length=20)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_comission', models.ForeignKey(db_column='id_comission', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'evaluation',
                'constraints': [models.UniqueConstraint(fields=('id_comission', 'id_soumission', 'id_utilisateur', 'type'), name='unique_evaluation_par_membre')],
            },
        ),
        migrations.CreateModel(
            name='MembresCommissionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('id_comission', models.ForeignKey(db_column='id_comission', on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'membres_commission_evaluation',
                'constraints': [models.UniqueConstraint(fields=('id_comission', 'id_utilisateur'), name='unique_membre_commission')],
            },
        ),
    ]
