# Generated by Django 5.1.6 on 2026-05-24 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrescommissionevaluation',
            name='role_label',
            field=models.CharField(choices=[('president', 'Président de séance'), ('secretaire', 'Secrétaire'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='type',
            field=models.CharField(choices=[('administrative', 'Administrative'), ('technique', 'Technique'), ('financiere', 'Financière')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pv', models.CharField(choices=[('ouverture', 'PV Ouverture'), ('evaluation', 'PV Évaluation')], max_length=15)),
                ('locked', models.BooleanField(default=False)),
                ('sent_to_sc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvs', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'proces_verbal',
                'unique_together': {('id_comission', 'type_pv')},
            },
        ),
        migrations.CreateModel(
            name='SCDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Accepté — Attribution provisoire'), ('rejected', 'Rejeté'), ('info_request', "Demande d'informations complémentaires")], max_length=15)),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('decided_by', models.IntegerField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_decisions', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'sc_decision',
            },
        ),
        migrations.CreateModel(
            name='SeanceOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('not_started', 'Non démarrée'), ('in_progress', 'En cours'), ('closed', 'Clôturée')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('anomalie', models.TextField(blank=True, default='')),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'seance_ouverture',
            },
        ),
        migrations.CreateModel(
            name='PliOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('montant_declare', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plis', to='evaluations_service.seanceouverture')),
            ],
            options={
                'db_table': 'pli_ouverture',
            },
        ),
        migrations.CreateModel(
            name='SignaturePV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('reserve', models.TextField(blank=True, default='')),
                ('has_reserve', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='evaluations_service.procesverbal')),
            ],
            options={
                'db_table': 'signature_pv',
            },
        ),
        migrations.CreateModel(
            name='CapacitesOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('items_results', models.JSONField(default=dict)),
                ('justification', models.TextField(blank=True, default='')),
                ('resultat', models.CharField(blank=True, choices=[('suffisant', 'Capacités suffisantes'), ('insuffisant', 'Capacités insuffisantes')], max_length=15, null=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacites', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'capacites_offer',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.CreateModel(
            name='ClassementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('rang', models.IntegerField()),
                ('score_technique', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('score_financier', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('score_combine', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ecarte_provisoire', models.BooleanField(default=False)),
                ('motif_ecart', models.TextField(blank=True, default='')),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classement', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'classement_entry',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.CreateModel(
            name='ConformiteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('enveloppe_anonyme', models.BooleanField(null=True)),
                ('documents_corrects', models.BooleanField(null=True)),
                ('pas_prix_technique', models.BooleanField(null=True)),
                ('eligible_art75', models.BooleanField(null=True)),
                ('complement_demande', models.BooleanField(default=False)),
                ('complement_motif', models.TextField(blank=True, default='')),
                ('resultat', models.CharField(blank=True, choices=[('admis', 'Admis'), ('ecarte', 'Écarté')], max_length=10, null=True)),
                ('motif_ecart', models.TextField(blank=True, default='')),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conformites', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'conformite_offer',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.CreateModel(
            name='EvalFinanciereOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('montant_declare', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('montant_bpu_calcule', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('correction_rule', models.CharField(blank=True, choices=[('unit_price', 'Prix unitaire prévaut'), ('total', 'Total déclaré prévaut')], max_length=15, null=True)),
                ('montant_corrige', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('marge_appliquee', models.BooleanField(default=False)),
                ('montant_evaluation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('refuse_correction', models.BooleanField(default=False)),
                ('refuse_motif', models.TextField(blank=True, default='')),
                ('locked', models.BooleanField(default=False)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals_financiere', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'eval_financiere_offer',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.CreateModel(
            name='EvalTechniqueOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('scores', models.JSONField(default=dict)),
                ('justifications', models.JSONField(default=dict)),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('qualifie', models.BooleanField(null=True)),
                ('locked', models.BooleanField(default=False)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals_technique', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'eval_technique_offer',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.CreateModel(
            name='ParapheMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('paraphed_at', models.DateTimeField(auto_now_add=True)),
                ('pli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraphes', to='evaluations_service.pliouverture')),
            ],
            options={
                'db_table': 'paraphe_membre',
                'unique_together': {('pli', 'id_utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='RegistreIntegriteConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by', models.IntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrite_confirmations', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'registre_integrite_confirmation',
                'constraints': [models.UniqueConstraint(fields=('id_comission',), name='unique_integrite_commission')],
            },
        ),
        migrations.CreateModel(
            name='RegistreReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_soumission', models.IntegerField()),
                ('numero_ordre', models.IntegerField()),
                ('nom_oe', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('hors_delai', models.BooleanField(default=False)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registre_entries', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'registre_reception',
                'unique_together': {('id_comission', 'id_soumission')},
            },
        ),
        migrations.AddConstraint(
            model_name='seanceouverture',
            constraint=models.UniqueConstraint(fields=('id_comission',), name='unique_seance_commission'),
        ),
        migrations.AlterUniqueTogether(
            name='pliouverture',
            unique_together={('seance', 'id_soumission')},
        ),
        migrations.AlterUniqueTogether(
            name='signaturepv',
            unique_together={('pv', 'id_utilisateur')},
        ),
    ]
