# Generated by Django 5.1.6 on 2026-05-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_service', '0002_membrescommissionevaluation_role_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignationCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations_ct', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'assignation_ct',
                'unique_together': {('id_comission', 'id_utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='RapportCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.IntegerField()),
                ('methodologie', models.TextField(blank=True, default='')),
                ('equipe', models.TextField(blank=True, default='')),
                ('materiels', models.TextField(blank=True, default='')),
                ('anomalies', models.TextField(blank=True, default='')),
                ('avis_global', models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('reserve', 'Avec réserves'), ('defavorable', 'Défavorable')], max_length=15, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_ct', to='evaluations_service.comissionevaluation')),
            ],
            options={
                'db_table': 'rapport_ct',
                'unique_together': {('id_comission', 'submitted_by')},
            },
        ),
    ]
