# Generated by Django 5.1.6 on 2026-05-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats_service', '0002_rename_id_organisation_to_id_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcontrat',
            name='id_contrat',
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
        migrations.DeleteModel(
            name='DocumentContrat',
        ),
    ]
