class DocumentService:

    def attach_document(self, recours_id: int, document_id: int): ...
    def detach_document(self, recours_id: int, document_id: int): ...
    def list_documents(self, recours_id: int): ...