# Generated by Django 6.0.2 on 2026-02-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateurEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=100)),
                ('registre_commerce_num', models.CharField(max_length=100)),
                ('casnos_vrt', models.CharField(max_length=100)),
                ('cnas_vrt', models.CharField(max_length=100)),
                ('rib_bancaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_officiel', models.CharField(max_length=20)),
                ('adresse_siege', models.CharField(max_length=100)),
                ('email_contact', models.EmailField(max_length=100)),
                ('type_entite', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_permission', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContractant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255)),
                ('code_ordonnateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tutelle', models.CharField(max_length=255)),
                ('identite_autorite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.role')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comission', models.CharField(max_length=255)),
                ('type_comission', models.CharField(choices=[('permanante', 'Permanante'), ('adhoc', 'Adhoc')], max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.servicecontractant')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comission', models.CharField(max_length=100)),
                ('niveau_competance', models.CharField(choices=[('communale', 'Communale'), ('wilaya', 'Wilaya'), ('sectorielle', 'Sectorielle'), ('nationale', 'Nationale')], max_length=20)),
                ('seuils_competence_financiere', models.CharField(max_length=255)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_service.servicecontractant')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comission', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.servicecontractant')),
            ],
        ),
        migrations.AddField(
            model_name='servicecontractant',
            name='tutelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.tutelle'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.organisation')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_service.role')),
            ],
        ),
        migrations.CreateModel(
            name='MembreCommissionInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_interne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.commissioninterne')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='MembreCommissionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.commissionevaluation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.utilisateur')),
            ],
        ),
    ]
