# Generated by Django 6.0.2 on 2026-02-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
        ('contract_service', '0001_initial'),
        ('tender_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=255)),
                ('type_document', models.CharField(max_length=50)),
                ('storage_url', models.CharField(max_length=500)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('is_encrypted', models.BooleanField()),
                ('ia_verif_statut', models.CharField(max_length=30)),
                ('ia_verif_details', models.TextField()),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.appeloffres')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra_service.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_service.contrat')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra_service.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRecours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra_service.document')),
                ('recours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_service.recours')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra_service.document')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entite_type', models.CharField(max_length=30)),
                ('entite_id', models.IntegerField()),
                ('horodatage', models.DateTimeField()),
                ('adresse_ip', models.CharField(max_length=45)),
                ('hash_log_precedent', models.CharField(max_length=64)),
                ('hash_log_actuel', models.CharField(max_length=64)),
                ('details_action', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priorite', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=50)),
                ('entite_liee_type', models.CharField(max_length=30)),
                ('entite_liee_id', models.IntegerField()),
                ('statut', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.utilisateur')),
            ],
        ),
    ]
