# Generated by Django 5.2.11 on 2026-03-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id_soumission', models.AutoField(primary_key=True, serialize=False)),
                ('id_appel_offre', models.IntegerField(help_text="Reference to the Appel d'Offre in the Appels Service")),
                ('id_soumissionnaire', models.IntegerField(help_text='Reference to the Entreprise/User in Auth Service')),
                ('offre_financiere_chiffree_url', models.URLField(help_text='MinIO URL of the encrypted PDF', max_length=500)),
                ('cle_dechiffrement_hash', models.TextField(help_text="AES Key encrypted with Appel d'Offre public RSA key")),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('EN_OUVERTURE', 'En Ouverture'), ('EN_EVALUATION', 'En Évaluation'), ('EVALU_TERMINEE', 'Évaluation Terminée'), ('RETRAITE', 'Retraitée')], default='SOUMIS', max_length=50)),
                ('montant_financier', models.DecimalField(blank=True, decimal_places=2, help_text='Filled ONLY after official opening of bids', max_digits=15, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('conformite_statut', models.CharField(blank=True, max_length=100, null=True)),
                ('conformite_rapport', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'soumissions',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('id_comission', models.IntegerField(help_text='ID of the Commission via Appels Service')),
                ('id_membre', models.IntegerField(help_text='ID of the Commission Member')),
                ('note', models.FloatField(help_text='Score out of 100')),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='soumissions_app.soumission')),
            ],
            options={
                'db_table': 'evaluations',
                'unique_together': {('id_soumission', 'id_membre')},
            },
        ),
    ]
