# Generated by Django 5.1.6 on 2026-05-09 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissions_app', '0004_alter_soumission_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionEvaluateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(choices=[('technique', 'Technique / Financière'), ('administrative', 'Administrative')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_a_evaluer', to=settings.AUTH_USER_MODEL)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluateurs_assignes', to='soumissions_app.soumission')),
            ],
            options={
                'db_table': 'soumission_evaluateur',
                'unique_together': {('soumission', 'evaluateur', 'type_evaluation')},
            },
        ),
    ]
