# Generated by Django 5.1.6 on 2026-05-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissions_app', '0005_soumissionevaluateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_contractant_id', models.IntegerField(db_index=True)),
                ('appel_id', models.IntegerField(db_index=True)),
                ('commission_id', models.IntegerField(db_index=True, help_text="ID de la commission chargée de valider l'attribution — même valeur que AppelOffres.commission_id")),
                ('validated_by', models.IntegerField(blank=True, null=True)),
                ('validation_level', models.CharField(choices=[('interne', 'Interne'), ('externe_wilaya', 'Externe Wilaya'), ('externe_secteur', 'Externe Secteur'), ('externe_nationale', 'Externe Nationale')], default='interne', max_length=30)),
                ('statut', models.CharField(choices=[('provisoire', 'Provisoire'), ('definitive', 'Définitive')], default='provisoire', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soumission', models.ForeignKey(db_column='soumission_id', on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='soumissions_app.soumission')),
            ],
            options={
                'db_table': 'attribution',
            },
        ),
    ]
