# Generated by Django 5.1.6 on 2026-05-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissions_app', '0006_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumissionevaluateur',
            name='id_comission',
            field=models.IntegerField(blank=True, help_text='Commission COPEO assigned to this soumission', null=True),
        ),
    ]
