from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_alter_auditlog_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS journaux_audit (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                utilisateur_id bigint NOT NULL,
                action varchar(100) NOT NULL,
                entite_type varchar(50) NOT NULL,
                entite_id bigint NOT NULL,
                horodatage timestamptz NOT NULL DEFAULT NOW(),
                adresse_ip inet NULL,
                details_action jsonb NOT NULL,
                hash_precedent bytea NOT NULL,
                hash_actuel bytea NOT NULL,
                signature bytea NULL
            );

            CREATE INDEX IF NOT EXISTS journaux_audit_utilisateur_id_idx
                ON journaux_audit (utilisateur_id);
            CREATE INDEX IF NOT EXISTS journaux_audit_entite_type_entite_id_idx
                ON journaux_audit (entite_type, entite_id);
            CREATE INDEX IF NOT EXISTS journaux_audit_horodatage_idx
                ON journaux_audit (horodatage);

            CREATE TABLE IF NOT EXISTS journaux_outbox (
                id uuid PRIMARY KEY,
                aggregate_type varchar(100) NOT NULL,
                aggregate_id varchar(255) NOT NULL,
                event_type varchar(150) NOT NULL,
                payload jsonb NOT NULL,
                status varchar(20) NOT NULL DEFAULT 'PENDING',
                trace_id varchar(128) NULL,
                created_at timestamptz NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS journaux_outbox_status_idx
                ON journaux_outbox (status);
            CREATE INDEX IF NOT EXISTS journaux_outbox_created_at_idx
                ON journaux_outbox (created_at);
            CREATE INDEX IF NOT EXISTS journaux_outbox_aggregate_idx
                ON journaux_outbox (aggregate_type, aggregate_id);
            CREATE INDEX IF NOT EXISTS journaux_outbox_event_status_idx
                ON journaux_outbox (event_type, status);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS journaux_outbox;
            DROP TABLE IF EXISTS journaux_audit;
            """,
        ),
    ]
