# Generated by Django 5.1.6 on 2026-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur_id', models.IntegerField()),
                ('type_notification', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priorite', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=50)),
                ('entite_liee_type', models.CharField(max_length=30)),
                ('entite_liee_id', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
