class RecoursException(Exception): ...
class InvalidStateTransition(RecoursException): ...
class DeadlineExceeded(RecoursException): ...
class DuplicateRecours(RecoursException): ...
class UnauthorizedAction(RecoursException): ...