class RecoursState:
    def instruire(self, recours): ...
    def prendre_decision(self, recours, decision: str): ...
    def accepter(self, recours): ...
    def rejeter(self, recours): ...
    def cloturer(self, recours): ...