# Generated by Django 5.1.6 on 2026-05-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractant_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commissionexterne',
            table=None,
        ),
        migrations.CreateModel(
            name='MembresCommissionExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membre', models.IntegerField(db_index=True)),
                ('id_comission_externe', models.ForeignKey(db_column='id_comission_externe', on_delete=django.db.models.deletion.CASCADE, related_name='membre_links', to='contractant_service.commissionexterne')),
            ],
            options={
                'db_table': 'Membres_Commission_Externe',
                'constraints': [models.UniqueConstraint(fields=('id_membre', 'id_comission_externe'), name='unique_membre_commission_externe')],
            },
        ),
    ]
