# Generated by Django 5.1.6 on 2026-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_service', '0002_anomalie_detection_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionanomalieia',
            name='niveau_severite',
            field=models.CharField(choices=[('ERROR', 'Erreur'), ('WARNING', 'Avertissement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='detectionanomalieia',
            name='statut_examen',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', "En cours d'examen"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté (faux positif)'), ('SIGNALE', 'Signalé à la tutelle')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='detectionanomalieia',
            name='type_anomalie',
            field=models.CharField(choices=[('MONTANT_FINANCIER_MANQUANT', 'Montant financier manquant'), ('MONTANT_INVALID', 'Montant invalide'), ('MONTANT_TROP_ELEVE', 'Montant trop élevé'), ('MONTANT_TROP_BAS', 'Montant trop bas'), ('SOUMISSION_HORS_DELAI', 'Soumission hors délai'), ('PRIX_ANORMALEMENT_BAS', 'Prix anormalement bas'), ('PRIX_ANORMALEMENT_ELEVE', 'Prix anormalement élevé'), ('DISPERSION_ANORMALE', 'Dispersion anormale des prix'), ('ROTATION_SOUMISSIONNAIRES', 'Rotation de soumissionnaires'), ('SAUCISSONNAGE_PROXIMITE_SEUIL', 'Proximité de seuil réglementaire'), ('SAUCISSONNAGE_TEMPOREL', 'Clustering temporel suspect'), ('SAUCISSONNAGE_CUMUL_SEUIL', 'Dépassement cumulé de seuil'), ('SAUCISSONNAGE_MEME_FOURNISSEUR', 'Même fournisseur multi-marchés')], db_index=True, max_length=50),
        ),
    ]
