# Generated by Django 6.0.2 on 2026-02-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_procedure', models.CharField(max_length=50)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_publication', models.DateTimeField()),
                ('date_limite_soumission', models.DateTimeField()),
                ('date_ouverture_plis', models.DateTimeField()),
                ('poids_technique', models.IntegerField()),
                ('poids_financier', models.IntegerField()),
                ('statut', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_contractant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.servicecontractant')),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField()),
                ('montant_financier', models.DecimalField(decimal_places=2, max_digits=15)),
                ('offre_financiere_chiffree_url', models.CharField(max_length=500)),
                ('cle_dechiffrement_hash', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=30)),
                ('conformite_statut', models.CharField(max_length=30)),
                ('conformite_rapport', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.appeloffres')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('administrative', 'Administrative'), ('technique', 'Technique'), ('financiere', 'Financiere')], max_length=20)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.commissionevaluation')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionAnomalieIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(max_length=50)),
                ('niveau_severite', models.CharField(max_length=20)),
                ('score_confiance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField()),
                ('statut_examen', models.CharField(max_length=30)),
                ('date_detection', models.DateTimeField()),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.appeloffres')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.soumission')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe'), ('tutelle', 'Tutelle')], max_length=20)),
                ('is_validated', models.BooleanField()),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_service.organisation')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_service.soumission')),
            ],
        ),
    ]
