class RecoursService:

    def create_recours(self, data: dict): ...
    def get_recours(self, recours_id: int): ...
    def list_recours(self, filters: dict): ...
    def delete_recours(self, recours_id: int): ...

    def instruire_recours(self, recours_id: int): ...
    def prendre_decision(self, recours_id: int, decision: str): ...
    def accepter_recours(self, recours_id: int): ...
    def rejeter_recours(self, recours_id: int): ...
    def cloturer_recours(self, recours_id: int): ...