# Generated by Django 5.1.6 on 2026-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_service', '0005_appeloffres_enrichment_and_achats_simples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsappel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
