# Generated by Django 5.1.6 on 2026-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_service', '0006_alter_documentsappel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='commission_id',
            field=models.IntegerField(db_index=True, default=123456, help_text='ID de la commission provenant du service externe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeloffres',
            name='validated_by',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID du membre ayant validé la demande', null=True),
        ),
        migrations.AddField(
            model_name='appeloffres',
            name='validation_level',
            field=models.CharField(choices=[('interne', 'Interne'), ('externe_wilaya', 'Externe Wilaya'), ('externe_secteur', 'Externe Secteur'), ('externe_nationale', 'Externe Nationale')], default='interne', max_length=30),
        ),
        migrations.AlterField(
            model_name='appeloffres',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non validé'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('ferme', 'Fermé')], default='non_valide', max_length=30),
        ),
    ]
