# Generated by Django 5.1.6 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appels_service", "0007_appeloffres_commission_id_appeloffres_validated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeloffres",
            name="secteur",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="id_operateur_choisi",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="id_doc_cdc",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="id_doc_justification",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="id_doc_besoin",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="appeloffres",
            name="etat_execution",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("publie", "Publie"),
                    ("depot_cloture", "Depot cloture"),
                    ("plis_ouverts", "Plis ouverts"),
                    ("annule", "Annule"),
                ],
                default="brouillon",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appeloffres",
            name="commission_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID de la commission provenant du service externe",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appeloffres",
            name="validated_by",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID du membre ayant valide la demande",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appeloffres",
            name="validation_level",
            field=models.CharField(
                choices=[
                    ("aucun", "Aucun"),
                    ("interne", "Interne"),
                    ("externe_wilaya", "Externe Wilaya"),
                    ("externe_secteur", "Externe Secteur"),
                    ("externe_nationale", "Externe Nationale"),
                ],
                default="interne",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appeloffres",
            name="poids_technique",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name="appeloffres",
            name="poids_financier",
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
