# Generated by Django 5.1.6 on 2026-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_service', '0008_appeloffres_procedure_rules_and_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffres',
            name='methodology',
            field=models.CharField(choices=[('price_only', 'Offre la moins disante'), ('weighted', 'Pondération technique+financière')], default='weighted', help_text='Méthodologie Art.72 — définie par le SC, immuable après publication', max_length=20),
        ),
        migrations.AddField(
            model_name='appeloffres',
            name='seuil_technique',
            field=models.IntegerField(default=70, help_text='Score minimum pour qualification technique (0-100)'),
        ),
        migrations.AlterField(
            model_name='appeloffres',
            name='type_procedure',
            field=models.CharField(choices=[('publique', 'Publique'), ('restreint', 'Restreint'), ('gre_a_gre', 'Gre a gre'), ('consultation', 'Consultation')], max_length=50),
        ),
    ]
