class RecoursDomainService:

    def verifier_unicite_recours(self, id_soumission: int): ...
    def verifier_delai(self, date_limite, date_actuelle): ...
    def verifier_proprietaire(self, operateur_id: int, soumission): ...